Repository optimas-org/optimas, pull requests merged in 2023-11, with the labels that each got.

#126 Disable Ax logs
  optimas/generators/ax/base.py
Labels: bug

#124 Improve multi-objective optimization and add support for fully Bayesian optimization
  optimas/generators/ax/service/single_fidelity.py
  tests/test_ax_generators.py
Labels: enhancement

#128 Enable manually adding trials and evaluations to `Exploration`
  optimas/explorations/base.py
  optimas/gen_functions.py
  optimas/generators/base.py
  optimas/utils/other.py
  tests/test_analyzed_parameters.py
  tests/test_ax_generators.py
  tests/test_exploration_resume.py
  tests/test_manual_exploration.py
Labels: enhancement

#138 Doc: Button to Copy Code Blocks
  doc/requirements.txt
  doc/source/conf.py
Labels: documentation

#139 CI: Blacken-Docs Version w/ Black
  .pre-commit-config.yaml
Labels: documentation

#141 Document new features and improve README
  README.md
  doc/source/user_guide/basic_usage/running_with_simulations.rst
Labels: documentation

#135 Use new libE save history options
  optimas/explorations/base.py
  pyproject.toml
  tests/test_exploration_resume.py
Labels: enhancement

#137 Reduce number of initialization evaluations if external data is supplied
  optimas/generators/ax/service/ax_client.py
  optimas/generators/ax/service/base.py
  optimas/generators/ax/service/multi_fidelity.py
  optimas/generators/ax/service/single_fidelity.py
  tests/test_ax_generators.py
Labels: enhancement
