Repository optimas-org/optimas, pull requests merged in 2024-04, with the labels that each got.

#190 README: Fix a Typo
  README.md
Labels: documentation

#187 Allow `FunctionEvaluator` to create evaluation dirs
  optimas/diagnostics/exploration_diagnostics.py
  optimas/evaluators/function_evaluator.py
  tests/test_function_evaluator.py
Labels: enhancement

#198 Run generator on manager
  optimas/diagnostics/ax_model_manager.py
  optimas/diagnostics/exploration_diagnostics.py
  optimas/explorations/base.py
  optimas/gen_functions.py
  optimas/generators/ax/developer/multitask.py
  optimas/generators/ax/service/base.py
  optimas/generators/base.py
  optimas/utils/other.py
  pyproject.toml
  tests/resources/template_simulation_script.py
  tests/test_ax_generators.py
  tests/test_gpu_resources.py
Labels: enhancement

#200 Fix bug when loading AxClient from json and require `Ax >= 0.3.5`
  doc/environment.yaml
  optimas/generators/ax/developer/multitask.py
  optimas/generators/ax/import_error_dummy_generator.py
  optimas/generators/ax/service/base.py
  pyproject.toml
  tests/test_ax_generators.py
Labels: bug
