Repository optimas-org/optimas, pull requests merged in 2024-02, with the labels that each got.

#175 Add methods to print information about the evaluations
  optimas/diagnostics/exploration_diagnostics.py
  tests/test_exploration_diagnostics.py
Labels: enhancement

#171 Fix bug in pandas dtype when converting from numpy
  optimas/utils/other.py
Labels: bug

#176 Expose `stdout` and `stderr` filenames to user
  optimas/evaluators/template_evaluator.py
  optimas/sim_functions.py
Labels: enhancement

#170 Add support for constraints in Ax generators using the Service API
  optimas/core/trial.py
  optimas/generators/ax/service/ax_client.py
  optimas/generators/ax/service/base.py
  optimas/generators/ax/service/multi_fidelity.py
  optimas/generators/ax/service/single_fidelity.py
  tests/test_ax_generators.py
Labels: enhancement

#164 Add evaluation timeout and improve handling of evaluations that failed to launch
  optimas/evaluators/template_evaluator.py
  optimas/sim_functions.py
  tests/resources/template_simulation_script.py
  tests/test_template_evaluator.py
Labels: enhancement

#154 Improve handling of failed evaluations
  optimas/core/__init__.py
  optimas/core/trial.py
  optimas/evaluators/base.py
  optimas/evaluators/multitask_evaluator.py
  optimas/explorations/base.py
  optimas/gen_functions.py
  optimas/generators/ax/developer/multitask.py
  optimas/generators/ax/service/ax_client.py
  optimas/generators/ax/service/base.py
  optimas/generators/ax/service/multi_fidelity.py
  optimas/generators/ax/service/single_fidelity.py
  optimas/generators/base.py
  optimas/generators/grid_sampling.py
  optimas/generators/line_sampling.py
  optimas/generators/random_sampling.py
  optimas/sim_functions.py
  tests/test_ax_generators.py
  tests/test_template_evaluator.py
Labels: enhancement

#177 Add conda-forge badge and update docs
  README.md
  doc/source/user_guide/dependencies.rst
  doc/source/user_guide/installation_juwels.rst
  doc/source/user_guide/installation_local.rst
  doc/source/user_guide/installation_maxwell.rst
  doc/source/user_guide/installation_perlmutter.rst
Labels: documentation

#179 Require `libEnsemble >= 1.2`
  pyproject.toml
Labels: enhancement
