Repository optimas-org/optimas, pull requests merged in 2024-01, with the labels that each got.

#142 Update HiPACE++ template script
  examples/hipace/template_simulation_script
Labels: documentation

#159 Fix typo in Maxwell installation instructions
  doc/source/user_guide/installation_maxwell.rst
Labels: bug

#158 Fix bug with fixed parameters
  optimas/generators/ax/service/base.py
  tests/test_ax_generators.py
Labels: bug

#167 Use Python 3.11 on Maxwell
  doc/source/user_guide/installation_maxwell.rst
Labels: documentation

#165 Add new plots and methods to `ExplorationDiagnostics`
  optimas/diagnostics/exploration_diagnostics.py
  tests/resources/template_simulation_script_moo.py
  tests/test_exploration_diagnostics.py
Labels: enhancement

#163 Keep trailing newline in template script
  optimas/sim_functions.py
Labels: bug

#168 Adds a new plot to `ExplorationDiagnostics`
  optimas/diagnostics/exploration_diagnostics.py
  optimas/explorations/base.py
  optimas/utils/other.py
  tests/test_exploration_diagnostics.py
Labels: enhancement

#173 Show evaluation indices of "top" simulations
  optimas/diagnostics/exploration_diagnostics.py
Labels: enhancement
