Repository optimas-org/optimas, pull requests merged in 2024-05, with the labels that each got.

#206 Add support for Ax `0.4.0`
  .github/workflows/unix-openmpi.yml
  .github/workflows/unix.yml
  doc/environment.yaml
  optimas/generators/ax/import_error_dummy_generator.py
  optimas/generators/ax/service/base.py
  optimas/generators/ax/service/custom_ax.py
  optimas/generators/ax/service/multi_fidelity.py
  pyproject.toml
Labels: bug

#169 Expose `AxModelManager` methods in Service API generators and add new plotting methods
  doc/source/api/diagnostics.rst
  doc/source/api/index.rst
  doc/source/api/utils.rst
  doc/source/user_guide/advanced_usage/build_gp_surrogates.ipynb
  optimas/diagnostics/__init__.py
  optimas/diagnostics/exploration_diagnostics.py
  optimas/explorations/base.py
  optimas/generators/ax/service/base.py
  optimas/utils/__init__.py
  optimas/utils/ax/__init__.py
  optimas/utils/ax/ax_model_manager.py
  optimas/utils/ax/other.py
  tests/test_ax_generators.py
  tests/test_ax_model_manager.py
Labels: enhancement

#211 Add ASTRA optimization example files
  doc/source/examples/bo_with_astra.rst
  doc/source/examples/index.rst
  examples/astra/ASTRA_example.in
  examples/astra/analysis_script.py
  examples/astra/run_optimization_serial_ASTRA.py
Labels: documentation
